NovoRad/Models/Anexo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace NovoRad.Models
{
    public class Anexo
    {
        public int AnexoId { get; set; }

        [Column(TypeName = "varchar(100)")]
        public string NomeAnexoUpload { get; set; }
        public DateTime DataAnexo  { get; set; }
        [Column(TypeName = "varchar(15)")]
        public string Autor { get; set; }

        [Column(TypeName = "varchar(300)")]
        public string DescricaoAnexo { get; set; }

        [Column(TypeName = "varchar(200)")]
        public string ContentType { get; set; }

        [Column(TypeName = "varbinary(MAX)")]
        public byte[] Bytes { get; set; }
        public int? TipoAnexoUploadId { get; set; }
        public TipoAnexo TipoAnexo { get; set; }
        public int? OcorrenciaId { get; set; }
        public Ocorrencia Ocorrencia { get; set; }
    }
}

NovoRad/Controllers/AnexosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NovoRad.Context;
using NovoRad.Models;
using NovoRad.Models.Notification;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace NovoRad.Controllers
{
    public class AnexosController : BaseController
    {

        private readonly AppDbContext _context;

        public AnexosController(AppDbContext context)
        {
            _context = context;
        }
        // GET: AnexosController
        public async Task<IActionResult> Index()
        {
            return View(await _context.Anexo.ToListAsync());
        }

        // GET: AnexosController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AnexosController/Create
        public IActionResult Create(int ocorrenciaId)
        {
            ViewBag.OcorrenciaId = ocorrenciaId;
            ViewBag.TipoAnexoId = new SelectList(_context.TipoAnexo, "TipoAnexoId", "NomeTipoAnexoUpload");
            return View();
        }

        // POST: AnexosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Anexo anexo, IFormFile postedFile, int ocorrenciaId)
        {
            if (postedFile == null)
            {
                return View(anexo);
            }

            if (ModelState.IsValid)
            {
                var userId = User.Identity.Name.Split("\\")[1];
                anexo.OcorrenciaId = ocorrenciaId;
                try
                {
                    byte[] bytes;
                    using (BinaryReader binaryReader = new BinaryReader(postedFile.OpenReadStream()))
                    {
                        bytes = binaryReader.ReadBytes((int)postedFile.Length);
                    }

                    var name = Path.GetFileName(postedFile.FileName);
                    var contentType = postedFile.ContentType;

                    anexo.NomeAnexoUpload = name;
                    anexo.Autor = userId;
                    anexo.ContentType = contentType;
                    anexo.Bytes = bytes;

                    _context.Anexo.Add(anexo);
                    await _context.SaveChangesAsync();
                    Notify(title: "OK!", message: "Anexo Adicionado Com Sucesso!", notificationType: Notification.success);
                    
                    return RedirectToAction("Edit", "Ocorrencias", new { id = ocorrenciaId });

                }
                catch (Exception ex)
                {
                    Notify(title: "Oops!", message: "Erro Ao Adicionar Anexo!", notificationType: Notification.warning);
                    return View();
                }
            }

            return View(anexo);
        }

        [HttpPost]
        public FileResult DownloadFile(int? fileId)
        {
            Anexo anexo = _context.Anexo.ToList().Find(p => p.AnexoId == fileId.Value);
            return File(anexo.Bytes, anexo.ContentType, anexo.NomeAnexoUpload);
        }

        // GET: AnexosController/Edit/5
        public async Task<IActionResult> Edit(int? id, int ocorrenciaId)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anexo = await _context.Anexo.FindAsync(id);
            if (anexo == null)
            {
                return NotFound();
            }

            ViewBag.OcorrenciaId = ocorrenciaId;
            ViewBag.TipoAnexoId = new SelectList(_context.TipoAnexo, "TipoAnexoId", "NomeTipoAnexoUpload");

            return View(anexo);
        }

        // POST: AnexosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Anexo anexo, IFormFile postedFile, int ocorrenciaId)
        {
            if (id != anexo.AnexoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var userId = User.Identity.Name.Split("\\")[1];

                try
                {
                    if (postedFile != null)
                    {
                        byte[] bytes;
                        using (BinaryReader binaryReader = new BinaryReader(postedFile.OpenReadStream()))
                        {
                            bytes = binaryReader.ReadBytes((int)postedFile.Length);
                        }

                        var name = Path.GetFileName(postedFile.FileName);
                        var contentType = postedFile.ContentType;

                        anexo.NomeAnexoUpload = name;
                        anexo.Autor = userId;
                        anexo.ContentType = contentType;
                        anexo.Bytes = bytes;
                    }

                    _context.Anexo.Update(anexo);
                    await _context.SaveChangesAsync();

                    Notify(title: "OK!", message: "Anexo Alterado Com Sucesso!", notificationType: Notification.success);
                    return RedirectToAction("Edit", "Ocorrencias", new { id = ocorrenciaId });

                }
                catch (Exception)
                {
                    Notify(title: "OK!", message: "Erro Ao Alterar Anexo!", notificationType: Notification.warning);
                    return View();
                }
            }

            return View(anexo);
        }
        // GET: AnexosController/Delete/5
        public async Task<IActionResult> Delete(int? id, int ocorrenciaId)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anexo = await _context.Anexo
                .FirstOrDefaultAsync(m => m.AnexoId == id);

            if (anexo == null)
            {
                return NotFound();
            }

            ViewBag.OcorrenciaId = ocorrenciaId;
            
            return View(anexo);
        }

        // POST: AnexosController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, int ocorrenciaId)
        {
            var userId = User.Identity.Name.Split("\\")[1];
            try
            {
                var anexo = await _context.Anexo.FindAsync(id);
                _context.Anexo.Remove(anexo);
                Notify(title: "OK!", message: "Anexo Deletado!", notificationType: Notification.success);
                await _context.SaveChangesAsync();
            }
            catch (Exception)
            {
                Notify(title: "OK!", message: "Erro Ao Deletar Anexo!", notificationType: Notification.error);
            }
            return RedirectToAction("Edit", "Ocorrencias", new { id = ocorrenciaId });
        }

        private bool AnexoExists(int id)
        {
            return _context.Anexo.Any(e => e.AnexoId == id);
        }
    }
}

NovoRad/Views/Anexos/Create.cshtml
@model NovoRad.Models.Anexo

@{
    ViewData["Title"] = "Novo Anexo";
}

<h4>Nova Evidência</h4>

<hr />

<form asp-action="Create" asp-route-ocorrenciaId="@ViewBag.OcorrenciaId" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label class="control-label">Anexar documento:</label>
                <input type="file" name="postedFile" class="form-control" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label asp-for="TipoAnexoUploadId" class="control-label">Tipo Anexo:</label>
            <select asp-for="TipoAnexoUploadId" type="text" class="form-control" asp-items="ViewBag.TipoAnexoId"></select>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label asp-for="DescricaoAnexo" class="control-label">Descrição:</label>
            <input asp-for="DescricaoAnexo" type="text" class="form-control" />
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Gravar</button>
</form>


@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/fstdropdown.min.js"></script>
}*@

NovoRad/Views/Anexos/Delete.cshtml
@model NovoRad.Models.Anexo

@{
    ViewData["Title"] = "Apagando Evidência";
}

<h3>Apagar anexo?</h3>
<a asp-action="Index">Voltar</a>
<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            Nome do Anexo:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NomeAnexoUpload)
        </dd>
        <dt class="col-sm-2">
            Data:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataAnexo)
        </dd>
        <dt class="col-sm-2">
            Autor:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
    </dl>

    <form asp-action="Delete" asp-route-ocorrenciaId="@ViewBag.OcorrenciaId">
        <input type="hidden" asp-for="AnexoId" />
        <input type="submit" value="Apagar" class="btn btn-danger" />
    </form>
</div>

NovoRad/Views/Anexos/Edit.cshtml
@model NovoRad.Models.Anexo

@{
    ViewData["Title"] = $"Editando {Model.NomeAnexoUpload}";
}

<h4>Editando @Model.NomeAnexoUpload</h4>
<hr />

<form asp-action="Edit" asp-route-ocorrenciaId="@ViewBag.OcorrenciaId" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <input type="hidden" asp-for="AnexoId"/>
    <input type="hidden" asp-for="NomeAnexoUpload" />
    <input type="hidden" asp-for="DataAnexo" />
    <input type="hidden" asp-for="Autor" />
    <input type="hidden" asp-for="Bytes" />
    <input type="hidden" asp-for="ContentType" />

    <div class="row">
        <div class="col">
            <div class="form-group">
                <label class="control-label">Anexar o novo documento:</label>
                <input type="file" name="postedFile" class="form-control" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label asp-for="TipoAnexoUploadId" class="control-label">Tipo Anexo:</label>
            <select asp-for="TipoAnexoUploadId" type="text" class="form-control" asp-items="ViewBag.TipoAnexoId"></select>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label asp-for="DescricaoAnexo" class="control-label">Descrição:</label>
            <input asp-for="DescricaoAnexo" type="text" class="form-control" />
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Gravar</button>
</form>

NovoRad/Views/Anexos/Index.cshtml
@model IEnumerable<NovoRad.Models.Anexo>

<table class="table table-hover alert-primary" style="border-radius: 1rem">
    <thead class="thead-dark">
        <tr>
            <th>
                Nome do Anexo
            </th>
            <th>
                Data
            </th>
            <th>
                Autor
            </th>
            <th>

            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeAnexoUpload)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataAnexo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Autor)
                </td>
                <td class="d-flex justify-content-between align-content-center">
                    @using (Html.BeginForm("DownloadFile", "Anexos", FormMethod.Post))
                    {
                        <input type="hidden" name="FileId" value="@item.AnexoId" multiple />
                        <button class="btn btn-icon text-success" type="submit">
                            <i class="fa fa-file-download"></i>
                        </button>
                    }
                    <a class="btn btn-icon text-primary" asp-controller="Anexos" asp-action="Edit" asp-route-id="@item.AnexoId" asp-route-ocorrenciaId="@item.OcorrenciaId">
                        <i class="fa fa-file-signature">Editar</i>
                    </a>
                    <a class="btn btn-icon text-danger" asp-controller="Anexos" asp-action="Delete" asp-route-id="@item.AnexoId" asp-route-ocorrenciaId="@item.OcorrenciaId">
                        <i class="fa fa-trash">Excluir</i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>