NovoRad/Models/Envolvido.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace NovoRad.Models
{
    public class Envolvido
    {
        public int EnvolvidoId { get; set; }
        public int? TipoEnvolvimentoId { get; set; }
        public TipoEnvolvimento TipoEnvolvimento { get; set; }

        [Column(TypeName = "varchar(25)")]
        public string CPF_CNPJ { get; set; }

        [Column(TypeName = "varchar(200)")]
        public string Nome { get; set; }

        [Column(TypeName = "varchar(25)")]
        public string? RG { get; set; }

        [Column(TypeName = "varchar(20)")]
        public string? Emissor { get; set; }

        [Column(TypeName = "varchar(2)")]
        public string? UF { get; set; }
        public bool PPE { get; set; }
        public DateTime? DataNascimento { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string? NomeMae { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string? NomePai { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string? Perfil { get; set; }
        [Column(TypeName = "varchar(15)")]
        public string? NumeroSAP { get; set; }
        [Column(TypeName = "varchar(15)")]
        public string? Login { get; set; }
        public int? AcaoTomadaId { get; set; }
        public AcaoTomada AcaoTomada { get; set; }
        public int? MedidaDisciplinarId { get; set; }
        public MedidaDisciplinar MedidaDisciplinar { get; set; }
        public int? EmpresaId { get; set; }
        public int OcorrenciaId { get; set; }
        public Ocorrencia Ocorrencia { get; set; }
        public ICollection<Endereco> Endereco { get; set; }
    }
}

NovoRad/Controllers/EnvolvidosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NovoRad.Context;
using NovoRad.Models;
using NovoRad.Models.Notification;
using NovoRad.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NovoRad.Controllers
{
    public class EnvolvidosController : BaseController
    {

        private readonly AppDbContext _context;

        public EnvolvidosController(AppDbContext context)
        {
            _context = context;
        }

        //GET: EnvolvidosController
        public async Task<IActionResult> Index()
        {
            var envolvidos = await _context.Envolvido
                .Include(e => e.AcaoTomada)
                .Include(e => e.MedidaDisciplinar)
                .Include(e => e.TipoEnvolvimento)
                .Include(e => e.Endereco)
                .ThenInclude(e => e.EnderecoId)
                .ToListAsync();


            //EnvolvidoEnderecoViewModel viewModelEnvolvido = new EnvolvidoEnderecoViewModel();
            //viewModelEnvolvido.Envolvidos = await _context.Envolvido
            //    .Include(e => e.AcaoTomada)
            //    .Include(e => e.MedidaDisciplinar)
            //    .Include(e => e.TipoEnvolvimento)
            //    .ToListAsync();
            //viewModelEnvolvido.Enderecos = _context.Endereco
            //    .Include(e => e.EnderecoId);

            return View(envolvidos);
        }

        public ActionResult Details()
        {
                
            return View();
        }

 
        public ActionResult Consulta(string cpfToFind)
        {
            if (cpfToFind == null)
            {
                return NotFound();
            }
            return View( _context.Envolvido
                .Include(e => e.AcaoTomada)
                .Include(e => e.MedidaDisciplinar)
                .Include(e => e.TipoEnvolvimento)
                .Where(e => e.CPF_CNPJ == cpfToFind)
                .ToList());

        }

        // GET: EnvolvidosController/Create
        public IActionResult Create(int ocorrenciaId)
        {


            ViewBag.OcorrenciaId = ocorrenciaId;
            ViewBag.TipoEnvolvimentoId = new SelectList(_context.TipoEnvolvimento, "TipoEnvolvimentoId", "NomeTipoEnvolvimento");
            ViewBag.AcaoTomadaId = new SelectList(_context.AcaoTomada, "AcaoTomadaId", "NomeAcaoTomada");
            ViewBag.MedidaDisciplinarId = new SelectList(_context.MedidaDisciplinar, "MedidaDisciplinarId", "NomeMedidaDisciplinar");

            return View();
        }

        // POST: EnvolvidosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Envolvido envolvido, int ocorrenciaId )
        {
            try
            {
                envolvido.OcorrenciaId = ocorrenciaId;
                _context.Add(envolvido);
                await _context.SaveChangesAsync();
                Notify(title: "OK!", message: "Envolvido Adicionado Com Sucesso!", notificationType: Notification.success);
                return RedirectToAction("Edit", "Ocorrencias");
            }
            catch
            {
                Notify(title: "Oops!", message: "Erro Ao Adicionar Envolvido!", notificationType: Notification.success);
                return View();
            }

        }

        // GET: EnvolvidosController/Edit/5
        public async Task<IActionResult> Edit(int? id, int ocorrenciaId)
        {
            if (id == null)
            {
                return NotFound();
            }

            ViewBag.EnvolvidoId = id;
            ViewBag.OcorrenciaId = ocorrenciaId;

            var envolvido = await _context.Envolvido
                .Include(e => e.Endereco)
                .FirstOrDefaultAsync(o => o.EnvolvidoId == id);
            //.FindAsync(id);


            //var envolvido = await _context.Envolvido
            //    .Include(e => e.Endereco)
            //    .ThenInclude(x => x.EnderecoId)
            //    .FirstOrDefaultAsync(e => e.EnvolvidoId == id);

            ViewBag.TipoEnvolvimentoId = new SelectList(_context.TipoEnvolvimento, "TipoEnvolvimentoId", "NomeTipoEnvolvimento");
            ViewBag.AcaoTomadaId = new SelectList(_context.AcaoTomada, "AcaoTomadaId", "NomeAcaoTomada");
            ViewBag.MedidaDisciplinarId = new SelectList(_context.MedidaDisciplinar, "MedidaDisciplinarId", "NomeMedidaDisciplinar");

            return View(envolvido);
        }

        // POST: EnvolvidosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Envolvido envolvido, int ocorrenciaId)
        {
            if (id != envolvido.EnvolvidoId)
            {
                return NotFound();
            }
            try
            {
                _context.Update(envolvido);
                await _context.SaveChangesAsync();
                Notify(title: "OK!", message: "Envolvido Alterado Com Sucesso!", notificationType: Notification.success);
                return RedirectToAction("Edit", "Ocorrencia", new { id = ocorrenciaId });
            }
            catch(Exception ex)
            {
                Notify(title: "Oops!", message: "Erro Ao Alterar Envolvido!", notificationType: Notification.warning);
                return View();
            }
        }

        // GET: EnvolvidosController/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var envolvido = await _context.Envolvido
                .Include(e => e.AcaoTomada)
                .Include(e => e.TipoEnvolvimento)
                .Include(e => e.MedidaDisciplinar)
                .FirstOrDefaultAsync(e => e.EnvolvidoId == id);


            if (envolvido == null)
            {
                return NotFound();
            }

            return View(envolvido);
        }

        // POST: EnvolvidosController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var envolvido = await _context.Envolvido.FindAsync(id);
                _context.Envolvido.Remove(envolvido);

                await _context.SaveChangesAsync();
                Notify(title: "OK!", message: "Conclusão Deletada!", notificationType: Notification.success);

            }
            catch (Exception ex)
            {
                Notify(title: "OK!", message: "Erro Ao Deletar Envolvido!", notificationType: Notification.warning);
            }
            return RedirectToAction(nameof(Index));
        }
    }

}

NovoRad/Views/Envolvidos/Consulta.cshtml
@model IEnumerable<NovoRad.Models.Envolvido>
@{
    ViewData["Title"] = "Consulta";
}

<h1>Consultar CPF</h1>

<form asp-action="Consulta">
    <div class="input-group">
        <label>Digite o CPF/CNPJ do envolvido:</label>
        <br />
        <input type="search" name="cpfToFind" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
        <button type="submit" class="btn btn-outline-primary">Search</button>
    </div>
</form>

<div class="row">
    @foreach (var item in Model)
    {
    <div class="col">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">Envolvido</h5>
                <p class="card-text">Nome: @Html.DisplayFor(modelItem => item.Nome)</p>
                <p class="card-text">CPF/CNPJ: @Html.DisplayFor(modelItem => item.CPF_CNPJ)</p>
                <p class="card-text">Data Nascimento: @Html.DisplayFor(modelItem => item.DataNascimento)</p>
                <p class="card-text">Tipo Envolvimento: @Html.DisplayFor(modelItem => item.TipoEnvolvimento.NomeTipoEnvolvimento)</p>
                <p class="card-text">Nome Pai: @Html.DisplayFor(modelItem => item.NomePai)</p>
                <p class="card-text">Nome Mãe: @Html.DisplayFor(modelItem => item.NomeMae)</p>
                <td>
                    <a class="btn btn-icon text-primary" asp-controller="Envolvidos" asp-action="Edit" asp-route-id="@item.EnvolvidoId" asp-route-ocorrenciaId="@item.OcorrenciaId">
                        <i class="fa fa-file-signature">Editar</i>
                    </a>
                    <a class="btn text-danger" asp-controller="Envolvidos" asp-action="Delete" asp-route-id="@item.EnvolvidoId">
                        <i class="fas fa-trash">Apagar</i>
                    </a>
                </td>
            </div>
        </div>
    </div>
    }
</div>

NovoRad/Views/Envolvidos/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Create";
}

@model NovoRad.Models.Envolvido

<form asp-action="Create" asp-route-ocorrenciaId="@ViewBag.OcorrenciaId" class="col">

    <div class="row">
        <h4>Novo Envolvido</h4>
    </div>
    <div class="row">
        <button onclick="location.href='/'" type="button" class="btn btn-link">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
            </svg> Voltar ao Início
        </button>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label asp-for="TipoEnvolvimentoId" class="control-label">Tipo Envolvimento</label>
                <select class="form-control input-validation-error" asp-for="TipoEnvolvimentoId" asp-items="ViewBag.TipoEnvolvimentoId"></select>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="CPF_CNPJ" class="control-label">CPF/CNPJ Envolvido</label>
                <input asp-for="CPF_CNPJ" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Nome" class="control-label">Nome</label>
                <input asp-for="Nome" type="text" class="form-control" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label asp-for="RG" class="control-label">RG</label>
                <input asp-for="RG" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label">Data de Nascimento</label>
                <input asp-for="DataNascimento" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Emissor" class="control-label">Emissor</label>
                <input asp-for="Emissor" type="datetime" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Perfil" class="control-label">Perfil</label>
                <input asp-for="Perfil" type="text" class="form-control" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label asp-for="UF" class="control-label">UF</label>
                <select class="form-control input-validation-error" asp-for="UF"></select>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="NomeMae" class="control-label">Nome da Mãe</label>
                <input asp-for="NomeMae" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="NomePai" class="control-label">Nome do Pai</label>
                <input asp-for="NomePai" type="text" class="form-control" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label asp-for="NumeroSAP" class="control-label">Número SAP</label>
                <input asp-for="NumeroSAP" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Login" class="control-label">Login</label>
                <input asp-for="Login" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="AcaoTomadaId" class="control-label">Ação Tomada</label>
                <select class="form-control input-validation-error" asp-for="AcaoTomadaId" asp-items="ViewBag.AcaoTomadaId"></select>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="MedidaDisciplinarId" class="control-label">Medida Disciplinar</label>
                <select class="form-control input-validation-error" asp-for="MedidaDisciplinarId" asp-items="ViewBag.MedidaDisciplinarId"></select>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-primary">Adicionar</button>
        </div>
    </div>

</form>

NovoRad/Views/Envolvidos/Delete.cshtml
@model NovoRad.Models.Envolvido
@{
    ViewData["Title"] = "Delete";
}

<h1>Deletar envolvido</h1>

<form asp-action="Delete">
    <input type="hidden" asp-for="EnvolvidoId" />
    <input type="submit" value="Apagar" class="btn btn-danger" />
</form>

NovoRad/Views/Envolvidos/Details.cshtml
@model NovoRad.Models.Envolvido
@{
    ViewData["Title"] = "Details";
}

<h1>Consultar CPF</h1>

<form asp-action="Consulta">
    <div class="input-group">
        <label>Digite o CPF/CNPJ do envolvido:</label>
        <br />
        <input type="search" name="cpfToFind" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
        <button type="submit" class="btn btn-outline-primary">Search</button>
    </div>
</form>


@*@foreach (var item in Model)
    {
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">Envolvido</h5>
                <p class="card-text">Nome: @Html.DisplayFor(modelItem => item.Nome)</p>
                <p class="card-text">CPF/CNPJ: @Html.DisplayFor(modelItem => item.CPF_CNPJ)</p>
                <p class="card-text">Data Nascimento: @Html.DisplayFor(modelItem => item.DataNascimento)</p>
                <p class="card-text">Tipo Envolvimento: @Html.DisplayFor(modelItem => item.TipoEnvolvimento.NomeTipoEnvolvimento)</p>
                <p class="card-text">Nome Pai: @Html.DisplayFor(modelItem => item.NomePai)</p>
                <p class="card-text">Nome Mãe: @Html.DisplayFor(modelItem => item.NomeMae)</p>
                <td>
                    <a class="btn btn-icon text-primary" asp-controller="Envolvidos" asp-action="Edit" asp-route-id="@item.EnvolvidoId" asp-route-ocorrenciaId="@item.OcorrenciaId">
                        <i class="fa fa-file-signature">Editar</i>
                    </a>
                    <a class="btn text-danger" asp-controller="Envolvidos" asp-action="Delete" asp-route-id="@item.EnvolvidoId">
                        <i class="fas fa-trash">Apagar</i>
                    </a>
                </td>
            </div>
        </div>
    }*@

NovoRad/Views/Envolvidos/Edit.cshtml
@model NovoRad.Models.Envolvido

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar envolvido</h1>

<form asp-action="Edit" asp-route-id="@ViewBag.EnvolvidoId" asp-route-ocorrenciaId="@ViewBag.OcorrenciaId" class="col">

    <div class="row">
        <h4>Novo Envolvido</h4>
    </div>

    @*escondido para passar no edit*@
    <label asp-for="EnvolvidoId" hidden></label>
    <input asp-for="EnvolvidoId" hidden type="text" />

    <div class="row">
        <button onclick="location.href='/'" type="button" class="btn btn-link">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
            </svg> Voltar ao Início
        </button>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label asp-for="TipoEnvolvimentoId" class="control-label">Tipo Envolvimento</label>
                <select class="form-control input-validation-error" asp-for="TipoEnvolvimentoId" asp-items="ViewBag.TipoEnvolvimentoId"></select>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="CPF_CNPJ" class="control-label">CPF/CNPJ Envolvido</label>
                <input asp-for="CPF_CNPJ" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Nome" class="control-label">Nome</label>
                <input asp-for="Nome" type="text" class="form-control" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label asp-for="RG" class="control-label">RG</label>
                <input asp-for="RG" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label">Data de Nascimento</label>
                <input asp-for="DataNascimento" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Emissor" class="control-label">Emissor</label>
                <input asp-for="Emissor" type="datetime" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Perfil" class="control-label">Perfil</label>
                <input asp-for="Perfil" type="text" class="form-control" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label asp-for="UF" class="control-label">UF</label>
                <select class="form-control input-validation-error" asp-for="UF"></select>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="NomeMae" class="control-label">Nome da Mãe</label>
                <input asp-for="NomeMae" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="NomePai" class="control-label">Nome do Pai</label>
                <input asp-for="NomePai" type="text" class="form-control" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label asp-for="NumeroSAP" class="control-label">Número SAP</label>
                <input asp-for="NumeroSAP" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Login" class="control-label">Login</label>
                <input asp-for="Login" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="AcaoTomadaId" class="control-label">Ação Tomada</label>
                <select class="form-control input-validation-error" asp-for="AcaoTomadaId" asp-items="ViewBag.AcaoTomadaId"></select>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="MedidaDisciplinarId" class="control-label">Medida Disciplinar</label>
                <select class="form-control input-validation-error" asp-for="MedidaDisciplinarId" asp-items="ViewBag.MedidaDisciplinarId"></select>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-primary">Adicionar</button>
        </div>
    </div>

</form>

<button class="bttn-unite bttn-sm bttn-primary mt-4" onclick="location.href='@(Url.Action("Create", "Endereco", new { envolvidoId = Model.EnvolvidoId }))'">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16">
        <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
        <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z" />
    </svg>
</button>


@if (Model.Endereco != null
&& Model.Endereco.Count > 0)
{
    await Html.RenderPartialAsync("~/Views/Endereco/Index.cshtml", Model.Endereco);
}
else
{
    <p>Nenhum envolvido cadastrado!</p>
}

NovoRad/Views/Envolvidos/Index.cshtml
@model IEnumerable<NovoRad.Models.Envolvido>


@foreach (var item in Model)
{
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">Envolvido</h5>
            <p class="card-text">Nome: @Html.DisplayFor(modelItem => item.Nome)</p>
            <p class="card-text">CPF/CNPJ: @Html.DisplayFor(modelItem => item.CPF_CNPJ)</p>
            <p class="card-text">Data Nascimento: @Html.DisplayFor(modelItem => item.DataNascimento)</p>
            <p class="card-text">Tipo Envolvimento: @Html.DisplayFor(modelItem => item.TipoEnvolvimento.NomeTipoEnvolvimento)</p>
            <p class="card-text">Nome Pai: @Html.DisplayFor(modelItem => item.NomePai)</p>
            <p class="card-text">Nome Mãe: @Html.DisplayFor(modelItem => item.NomeMae)</p>
            <td>
                <a class="btn btn-icon text-primary" asp-controller="Envolvidos" asp-action="Edit" asp-route-id="@item.EnvolvidoId" asp-route-ocorrenciaId="@item.OcorrenciaId">
                    <i class="fa fa-file-signature">Editar</i>
                </a>

            </td>
        </div>
    </div>

    @*@if (Model.Envolvido != null)
        {
            await Html.RenderPartialAsync("~/Views/Endereco/Index.cshtml", Model.Endereco);
        }
        else
        {
            <p>Nenhum envolvido cadastrado!</p>
        }*@
}
@*<button class="bttn-unite bttn-sm bttn-primary mt-4" onclick="location.href='@(Url.Action("Create", "Endereco", new { envolvidoId = Model.))'">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16">
        <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
        <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z" />
    </svg>
</button>*@