NovoRad/Models/Endereco.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NovoRad.Models
{
    public class Endereco
    {
        public int EnderecoId { get; set; }
        public string Logradouro { get; set; }
        public string Numero { get; set; }
        public string Complemento  { get; set; }
        public string Cep { get; set; }
        public string Bairro  { get; set; }
        public string Cidade  { get; set; }
        public string Estado  { get; set; }
        public int EnvolvidoId { get; set; }
        public Envolvido Envolvido { get; set; }
    }
}

NovoRad/Controllers/EnderecoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NovoRad.Context;
using NovoRad.Models;
using NovoRad.Models.Notification;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NovoRad.Controllers
{
    public class EnderecoController : BaseController
    {

        private readonly AppDbContext _context;

        public EnderecoController(AppDbContext context)
        {
            _context = context;
        }

        // GET: EnderecoController
        public async Task<IActionResult> Index()
        {
            var enderecos = await _context.Endereco.ToListAsync();
            return View(enderecos);
        }

        // GET: EnderecoController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: EnderecoController/Create
        public IActionResult Create(int envolvidoId)
        {
            ViewBag.EnvolvidoId = envolvidoId;
            return View();
        }

        // POST: EnderecoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Endereco endereco, int envolvidoId)
        {
            try
            {
                endereco.EnvolvidoId = envolvidoId;
                _context.Add(endereco);
                await _context.SaveChangesAsync();
                Notify(title: "OK!", message: "Endereço Adicionado Com Sucesso!", notificationType: Notification.success);
                return RedirectToAction("Edit", "Ocorrencias");
            }
            catch(Exception ex)
            {
                Notify(title: "Oops!", message: "Erro Ao Adicionar Endereço!", notificationType: Notification.warning);
                return View();
            }
        }

        // GET: EnderecoController/Edit/5
        public async Task<IActionResult> Edit(int? id, int envolvidoId)
        {
            if (id == null)
            {
                return NotFound();
            }

            ViewBag.EnderecoId = id;
            ViewBag.EnvolvidoId = envolvidoId;

            var endereco = await _context.Endereco.FindAsync(id);

            return View(endereco);
        }

        // POST: EnderecoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Endereco endereco, int envolvidoId)
        {
            if (id != endereco.EnderecoId)
            {
                return NotFound();
            }
            try
            {
                _context.Update(endereco);
                await _context.SaveChangesAsync();
                Notify(title: "OK!", message: "Endereço Alterado Com Sucesso!", notificationType: Notification.success);
                return RedirectToAction("Edit", "Ocorrencia", new { id = envolvidoId });
            }
            catch(Exception ex)
            {
                Notify(title: "Oops!", message: "Erro Ao Alterar Endereço!", notificationType: Notification.warning);
                return View();
            }
        }

        // GET: EnderecoController/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var endereco = await _context.Endereco
                .FirstOrDefaultAsync(e => e.EnderecoId == id);

            if (endereco == null)
            {
                return NotFound();
            }

            return View(endereco);

        }

        // POST: EnderecoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var endereco = await _context.Endereco.FindAsync(id);
                _context.Endereco.Remove(endereco);
                Notify(title: "OK!", message: "Endereço Deletado Com Sucesso!", notificationType: Notification.success);
                await _context.SaveChangesAsync();

            }
            catch (Exception ex)
            {
                Notify(title: "Oops!", message: "Erro Ao Deletar Endereço!", notificationType: Notification.success);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

NovoRad/Views/Endereco/Create.cshtml
@model NovoRad.Models.Endereco

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<form asp-action="Create" asp-route-envolvidoId="@ViewBag.EnvolvidoId" class="col">

    <div class="row">
        <h4>Novo Endereço</h4>
    </div>

    <div class="row">
        <div class="col">
            <div class="form-group">
                <label asp-for="Logradouro" class="control-label">Logradouro</label>
                <input asp-for="Logradouro" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Numero" class="control-label">Número</label>
                <input asp-for="Numero" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Complemento" class="control-label">Complemento</label>
                <input asp-for="Complemento" type="text" class="form-control" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label asp-for="Cep" class="control-label">CEP</label>
                <input asp-for="Cep" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Bairro" class="control-label">Bairro</label>
                <input asp-for="Bairro" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Estado" class="control-label">UF</label>
                <select class="form-control input-validation-error" asp-for="Estado" id="uf"></select>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Cidade" class="control-label">Cidade</label>
                <select class="form-control input-validation-error" asp-for="Cidade" id="cidade"></select>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-primary">Adicionar</button>
        </div>
    </div>

</form>

@section Scripts {
    <script src="~/js/site.js" asp-append-version="true"></script>
}

NovoRad/Views/Endereco/Delete.cshtml
@model NovoRad.Models.Endereco
@{
    ViewData["Title"] = "Delete";
}

<h1>Deletar endereço</h1>

<form asp-action="DeleteConfirmed">
    <input type="hidden" asp-for="EnderecoId" />
    <input type="submit" value="Apagar" class="btn btn-danger" />
</form>

NovoRad/Views/Endereco/Edit.cshtml
@model NovoRad.Models.Endereco
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<form asp-action="Edit" asp-route-id="@ViewBag.EnderecoId" asp-route-envolvidoId="@ViewBag.EnvolvidoId" class="col">

    <div class="row">
        <h4>Novo Endereço</h4>
    </div>

    <label asp-for="EnderecoId" hidden></label>
    <input asp-for="EnderecoId" hidden type="text" />

    <div class="row">
        <div class="col">
            <div class="form-group">
                <label asp-for="Logradouro" class="control-label">Logradouro</label>
                <input asp-for="Logradouro" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Numero" class="control-label">Número</label>
                <input asp-for="Numero" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Complemento" class="control-label">Complemento</label>
                <input asp-for="Complemento" type="text" class="form-control" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label asp-for="Cep" class="control-label">CEP</label>
                <input asp-for="Cep" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Bairro" class="control-label">Bairro</label>
                <input asp-for="Bairro" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Estado" class="control-label">UF</label>
                <select class="form-control input-validation-error" asp-for="Estado" id="uf"></select>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="Cidade" class="control-label">Cidade</label>
                <select class="form-control input-validation-error" asp-for="Cidade" id="cidade"></select>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-primary">Atualizar</button>
        </div>
    </div>

</form>

@section Scripts {
    <script src="~/js/site.js" asp-append-version="true"></script>
}

NovoRad/Views/Endereco/Index.cshtml
@model IEnumerable<NovoRad.Models.Endereco>

@{
    ViewData["Title"] = "Index";
}

<h1>Endereco</h1>

@foreach (var item in Model)
{
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">Endereço</h5>
            <p class="card-text">@Html.DisplayFor(modelItem => item.Logradouro),@Html.DisplayFor(modelItem => item.Numero)</p>
            <p class="card-text">@Html.DisplayFor(modelItem => item.Cep)</p>
            <p class="card-text">@Html.DisplayFor(modelItem => item.Cidade)-@Html.DisplayFor(modelItem => item.Estado)</p>
            <td>
                <a class="btn btn-icon text-primary" asp-controller="Endereco" asp-action="Edit" asp-route-id="@item.EnderecoId" asp-route-envolvidoId="@item.EnvolvidoId">
                    <i class="fa fa-file-signature">Editar</i>
                </a>
                <a class="btn text-danger" asp-controller="Endereco" asp-action="Delete" asp-route-id="@item.EnderecoId">
                    <i class="fas fa-trash">Apagar</i>
                </a>
            </td>
        </div>
    </div>
}