NovoRad/Models/Tarefa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace NovoRad.Models
{
    public class Tarefa
    {
        public int TarefaId { get; set; }

        public int? UsuarioId { get; set; }
        public Usuario Usuario { get; set; }

        public int? DiasPrazoId { get; set; }

        public DiasPrazo DiasPrazo { get; set; }

        [Column(TypeName = "varchar(200)")]
        public string AcaoTomada { get; set; }
        public DateTime DataInicio { get; set; }
        public int OcorrenciaId { get; set; }
        public Ocorrencia Ocorrencia { get; set; }
    }
}

NovoRad/Controllers/TarefasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NovoRad.Context;
using NovoRad.Models;
using NovoRad.Models.Notification;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NovoRad.Controllers
{
    public class TarefasController : BaseController
    {

        private readonly AppDbContext _context;

        public TarefasController(AppDbContext context)
        {
            _context = context;
        }
        // GET: TarefasController
        public async Task<IActionResult> Index()
        {
            var tarefas = await _context.Tarefa
                .Include(t => t.DiasPrazo)
                .Include(t => t.Usuario)
                .ToListAsync();
            return View(tarefas);
        }

        // GET: TarefasController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TarefasController/Create
        public IActionResult Create(int ocorrenciaId)
        {

            ViewBag.OcorrenciaId = ocorrenciaId;
            ViewBag.DiasPrazoId = new SelectList(_context.DiasPrazo, "DiasPrazoId", "NomeDiasPrazo");
            ViewBag.UsuarioId = new SelectList(_context.Usuario, "UsuarioId", "NomeUsuario");

            return View();
        }

        // POST: TarefasController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Tarefa tarefa, int ocorrenciaId)
        {
            try
            {
                tarefa.OcorrenciaId = ocorrenciaId;
                _context.Add(tarefa);
                await _context.SaveChangesAsync();
                Notify(title: "OK!", message: "Tarefa Adicionada Com Sucesso!", notificationType: Notification.success);
                return RedirectToAction("Edit", "Ocorrencias");
            }
            catch(Exception ex)
            {
                Notify(title: "Oops!", message: "Erro Ao Adicionar Tarefa!", notificationType: Notification.success);
                return View();
            }

        }

        // GET: TarefasController/Edit/5
        public async Task<IActionResult> Edit(int? id, int ocorrenciaId)
        {
            if (id == null)
            {
                return NotFound();
            }

            ViewBag.TarefaId = id;
            ViewBag.OcorrenciaId = ocorrenciaId;

            var tarefa = await _context.Tarefa
                .Include(e => e.DiasPrazo)
                .FirstOrDefaultAsync(o => o.TarefaId == id);

            ViewBag.DiasPrazoId = new SelectList(_context.DiasPrazo, "DiasPrazoId", "NomeDiasPrazo");
            return View(tarefa);
        }

        // POST: TarefasController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Tarefa tarefa, int ocorrenciaId)
        {
            if (id != tarefa.TarefaId)
            {
                return NotFound();
            }
            try
            {
                _context.Update(tarefa);
                await _context.SaveChangesAsync();
                Notify(title: "OK!", message: "Tarefa Alterada Com Sucesso!", notificationType: Notification.success);
                return RedirectToAction("Edit", "Ocorrencia", new { id = ocorrenciaId });
            }
            catch (Exception ex)
            {
                Notify(title: "Oops!", message: "Erro Ao Alterar Tarefa!", notificationType: Notification.warning);
                return View();
            }
        }

        // GET: TarefasController/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarefa = await _context.Tarefa
                .Include(t => t.DiasPrazo)
                .FirstOrDefaultAsync(e => e.TarefaId == id);


            if (tarefa == null)
            {
                return NotFound();
            }

            return View(tarefa);
        }
        // POST: TarefasController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var tarefa = await _context.Tarefa.FindAsync(id);
                _context.Tarefa.Remove(tarefa);

                await _context.SaveChangesAsync();
                Notify(title: "OK!", message: "Tarefa Deletada Com Sucesso!", notificationType: Notification.success);
            }
            catch (Exception ex)
            {
                Notify(title: "Oops!", message: "Erro Ao Deletar Tarefa!", notificationType: Notification.warning);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

NovoRad/Views/Tarefas/Create.cshtml
@model NovoRad.Models.Tarefa
@{
    ViewData["Title"] = "Create";
}

<form asp-action="Create" asp-route-ocorrenciaId="@ViewBag.OcorrenciaId" class="col">

    <div class="row">
        <h4>Nova Tarefa</h4>
    </div>
    <div class="row">
        <button onclick="location.href='/'" type="button" class="btn btn-link">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
            </svg> Voltar ao Início
        </button>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label asp-for="UsuarioId" class="control-label">Analista</label>
                <select class="form-control input-validation-error"  asp-for="UsuarioId" asp-items="ViewBag.UsuarioId"></select>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="DiasPrazoId" class="control-label">Dias Prazo:</label>
                <select class="form-control input-validation-error" asp-for="DiasPrazoId" asp-items="ViewBag.DiasPrazoId"></select>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="AcaoTomada" class="control-label">Ação a ser tomada</label>
                <input asp-for="AcaoTomada" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="DataInicio" class="control-label">Data Início</label>
                <input asp-for="DataInicio" type="date" class="form-control" />
            </div>
        </div>

    </div>

   

    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-primary">Adicionar</button>
        </div>
    </div>

</form>

NovoRad/Views/Tarefas/Delete.cshtml
@model NovoRad.Models.Tarefa

@{
    ViewData["Title"] = "Delete";
}

<h1>Deletar Tarefa</h1>

<form asp-action="Delete">
    <input type="hidden" asp-for="TarefaId" />
    <input type="submit" value="Apagar" class="btn btn-danger" />
</form>

NovoRad/Views/Tarefas/Edit.cshtml
@model NovoRad.Models.Tarefa
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<form asp-action="Edit" asp-route-ocorrenciaId="@ViewBag.OcorrenciaId" class="col">

    <div class="row">
        <h4>Nova Tarefa</h4>
    </div>
    <div class="row">
        <button onclick="location.href='/'" type="button" class="btn btn-link">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
            </svg> Voltar ao Início
        </button>
    </div>

    <label asp-for="TarefaId" class="control-label" hidden></label>
    <input asp-for="TarefaId" type="text" class="form-control" hidden/>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label asp-for="UsuarioId" class="control-label">Analista</label>
                <select class="form-control input-validation-error" asp-for="UsuarioId" asp-items="ViewBag.UsuarioId"></select>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="DiasPrazoId" class="control-label">Dias Prazo:</label>
                <select class="form-control input-validation-error" asp-for="DiasPrazoId" asp-items="ViewBag.DiasPrazoId"></select>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="AcaoTomada" class="control-label">Ação a ser tomada</label>
                <input asp-for="AcaoTomada" type="text" class="form-control" />
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="DataInicio" class="control-label">Data Início</label>
                <input asp-for="DataInicio" type="date" class="form-control" />
            </div>
        </div>

    </div>



    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-primary">Adicionar</button>
        </div>
    </div>

</form>

NovoRad/Views/Tarefas/Index.cshtml
@model IEnumerable<NovoRad.Models.Tarefa>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table table-hover alert-primary" style="border-radius: 1rem" id="myTable">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Data Início</th>
            <th scope="col">Demandante</th>
            <th scope="col">Dias Prazo</th>
            <th scope="col">Témino</th>
            <th scope="col">Editar</th>
            <th scope="col">Excluir</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@Html.DisplayFor(modelItem => item.TarefaId)</th>
                <td>@Html.DisplayFor(modelItem => item.DataInicio)</td>
                <td>@Html.DisplayFor(modelItem => item.Usuario.NomeUsuario)</td>
                <td>@Html.DisplayFor(modelItem => item.DiasPrazo.NomeDiasPrazo)</td>
                <td></td>
                <td>
                    <a class="btn btn-icon text-primary" asp-controller="Tarefas" asp-action="Edit" asp-route-id="@item.TarefaId" asp-route-ocorrenciaId="@item.OcorrenciaId">
                        <i class="fa fa-file-signature">Editar</i>
                    </a>
                </td>
                <td>
                    <a class="btn text-danger" asp-controller="Tarefas" asp-action="Delete" asp-route-id="@item.TarefaId">
                        <i class="fas fa-trash">Apagar</i>
                    </a>
                </td>
            </tr>
        }

    </tbody>
</table>